### ISSUE TITLE
Send setLimit

### ISSUE THREAD

**Issue by mplis** [sailthru/sailthru-java-client#45]
What do the [various `setLimit` functions](https://github.com/sailthru/sailthru-java-client/blob/b2baa5b1346d71ad8a6d72eeb9e2ddb4a2d57d35/src/main/com/sailthru/client/params/Send.java#L60) on the `Send` class do? There aren't any comments in the code explaining their purpose and I can't find any evidence of that parameter in the [docs](http://getstarted.sailthru.com/new-for-developers-overview/email-and-user-profiles/send/).

**Comment by eweiser** [comment]
Hi there, apologies for the delay. These functions have to do with a deprecated feature around transactionals. We will add comments shortly to clarify the deprecation (hence why they're no longer in the docs). Thanks for calling this out.
